#!/bin/bash
# Get the directory of this script
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Run using the local virtual environment Python interpreter
exec "$DIR/venv/bin/python" "$DIR/main.py" "$@"
